### ISSUE TITLE
Specify the folder inside a bucket where the files can be uploaded

### ISSUE THREAD

**Issue by peterSnS** [ChenglongMa/skipper-gcstorage#5]
Is there any way  to specify the folder inside the buckets that the uploaded files should go to?, they are going in the main  bucket for me

**Comment by ChenglongMa** [comment]
Hi @peterSnS, thanks for your issue.

Currently, the default `upload` function in sails implements a unique filename by combining a generated UUID and the file's original extension, e.g., ("/your/path/file.jpg" => "4d5f444-38b4-4dc3-b9c3-74cb7fbbc932.jpg"). I guess that's why the "folder" info was overridden. 

I will try to fix this issue in the next patch. Thanks!

**Comment by jungalwala** [comment]
Any update on this?

**Comment by ChenglongMa** [comment]
Now, you can use `keepName` option to set a customized filename in the bucket. As GCP does not support folders, you can set a long filename such as 'path/to/your/file'.

Thanks.
